name: PointPlugin
version: 1.2.1
main: com.rei.pointplugin.Main
api-version: "1.21"

commands:
  ranking:
    description: Show point ranking
    usage: /ranking

permissions:
  pointplugin.admin:
    description: Allow creating PointShop signs
    default: op
